### ISSUE TITLE
'About Us' page doesn't exist

### ISSUE THREAD

**Issue by szeckirjr** [SENG426-Team4/vega-web#1]
# Description
When the about page is clicked, nothing happens.

# Origin of bug
Initial Requirement Specification analysis.

# Steps to reproduce
Click on 'About Us' in menubar -> Nothing happens

# Story Points: 1
# Priority: medium

**Comment by AlessandroCipolletti** [comment]
Hi @szeckirjr Can I help? Can I take this one ?

**Comment by AlessandroCipolletti** [comment]
Can I ask you something, It's ok if I use the SimplePageLayout to create this new page ?
